# :::    ::: ::::    ::::  :::::::::
# :+:    :+: +:+:+: :+:+:+ :+:    :+:
# +:+    +:+ +:+ +:+:+ +:+ +:+    +:+
# +#++:++#++ +#+  +:+  +#+ +#++:++#+   ____  _  _    ____  _  _   __  __    __ _
# +#+    +#+ +#+       +#+ +#+        (  _ \( \/ )  (    \( \/ ) /  \(  )  (  / )
# #+#    #+# #+#       #+# #+#        ) _ ( )  /    ) D (/ \/ \(_/ // (_/\ )  (
# ###    ### ###       ### ###       (____/(__/    (____/\_)(_/ (__)\____/(__\_)

# Version 1.0.0

settings:
  # Send a custom message on first join!
  first-join-msg: true
  # Configuration for what happens on player death.
  death:
    # Strike the player with lightning when they die?
    lightning: true
    # Broadcast their death to the server?
    broadcast: 'MESSAGE'
  # Sets the name of the permission group used to set ghost permissions.
  ghost-permission-group: "dead"
  # Configuration for the revival sequence.
  revival:
    # Broadcast their revival to the server? (NONE, TITLE, ACTIONBAR, BOSSBAR, MESSAGE)
    broadcast: 'MESSAGE'
# Plugin Messages
messages:
  death: '&c☠&l %cause%'
  already-dead: '&7☠&l %cause%'
  revive-message: '&a❤&l %player% has been revived!'
  first-join: '§a❤§l %player% has been summoned by the revive machine!'
  admin:
    admin-revive: "&a❤&l Magical forces have brought %player% back from the dead!"
    already-alive: "&7&o %player% is already alive!"
    become-ghost: "&c☠&l Dark forces have dragged %player% into the afterlife!"
    already-ghost: "&7&o %player% is already a ghost!"
    give-book: "&c❤&l You're received a revive book!"
    receive-book: "&7&o A revive book was given to %player%"
config-version: 1
